#!/usr/bin/env bash
#
# Run all dotfiles installers.
export ZSH=$HOME/.dotfiles

set -e

cd "$(dirname $0)"/..

# Run brew-install first to ensure that Homebrew is installed and up-to-date
$ZSH/homebrew/brew-install.sh 2>&1

# Find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
